# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

# Google APIs
gem 'google-apis-analyticsdata_v1beta', '~> 0.40'
gem 'google-apis-searchconsole_v1', '~> 0.18'
gem 'googleauth', '~> 1.8'

# HTTP clients
gem 'faraday', '~> 2.7'
gem 'faraday-retry', '~> 2.2'

# Data processing
gem 'matrix', '~> 0.4'  # For clustering calculations

# Text analysis
gem 'nokogiri', '~> 1.15'  # HTML parsing
gem 'stopwords-filter', '~> 0.4'  # Stop words removal

# Configuration
gem 'dotenv', '~> 2.8'

# JSON handling
gem 'oj', '~> 3.16'  # Fast JSON parser

# Caching
gem 'diskcached', '~> 1.0'

# Development & Testing
group :development, :test do
  gem 'minitest', '~> 5.20'
  gem 'webmock', '~> 3.19'
  gem 'vcr', '~> 6.2'
  gem 'rubocop', '~> 1.57'
  gem 'rubocop-minitest', '~> 0.35'
  gem 'simplecov', '~> 0.22'
  gem 'pry', '~> 0.14'
end
